%%%NOTE: for help with latex symbols look here http://mirror.unl.edu/ctan/info/symbols/comprehensive/symbols-a4.pdf.
\documentclass[12pt]{article}
\usepackage{color}
\usepackage{cite}
\usepackage{geometry}                % See geometry.pdf to learn the layout options. There are lots.
%\usepackage{pdflscape}        %single page landscape
                                %mode \begin{landscape} \end{landscape}
\geometry{letterpaper}                   % ... or a4paper or a5paper or ... 
%\usepackage[parfill]{parskip}    % Activate to begin paragraphs with an empty line rather than an indent
\usepackage{multicol} % \begin{multicols}{number of columns} \end{multicols}
% \usepackage{lineno} %add lines numbers 
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{Sweave}
\newcommand{\etal}{\textit{et al.}}
\usepackage{hyperref}  %\hyperref[label_name]{''link text''}
                       %\hyperlink{label}{anchor caption}
                       %\hypertarget{label}{link caption}
\linespread{1.5}

\title{JoE Invited Paper}
\author{M.K. Lau}
%\date{}                                           % Activate to display a given date or no date

\begin{document}
\maketitle
%\linenumbers %%add line numbers

%\setcounter{tocdepth}{3}  %%activate to number sections
%\tableofcontents

%\thispagestyle{empty}
%\setcounter{page}{0}
%\setcounter{secnumdepth}{-1}  %activate to start numbering from one
%on the second page

\section{12 June 2014}
Use the Pairwise... excel file. 

\begin{verbatim}

Hey, thanks for the input.  I will incorporate it and plan to send out
another draft, this time to everyone, by the end of this weekend. One
thing we need to keep in mind with all of this (and I have to
continually remind Tom this too) is that the correlations could also
be due to shared underlying influences of genes or correlated genes
(i.e., pleiotrophy and linkage disequilibrium) and not interactions.

Attached are updated matrices for raw mantels among communities and
ones done with relativization. Could you make a new network figure for
each?  The bold+italicize are P less than or equal to 0.05 and the
ones only bolded are P is less than 1 and greater than 0.05. This
time, I think it would be nice to make the significant ones have black
lines, the marginal have dark grey lines and the insigificant ones
still be in the fig but have super light grey connections.  Just make
each network a different pdf and I can put them together in final
form. Also, Todd's webs suck.

One more task. The comparison of the raw to the relativized values
represents a test of one of Tom's hypotheses. So, I would like to
actually do a test, in addition to qualitatively comparing them. I
think this could be done by unfolding the matrices and performing a
paired t-test using a randomization procedure to get the p-value.
Could you do that?

Thanks
Jamie
\end{verbatim}

\section{06 June 2014}

Looking into analyses and visualzations of the relationships among
communities via the partial mantel coefficients.


\section{27 Mar 2014}
<<>>=
###Checking the matching of genotypes
source('../src/func_town.R')
library(ComGenR)
x <- read.csv('../data/emf06matchPFLA04.csv')
y <- read.csv('../data/emf06matchPFLA04_y.csv')
x. <- matchMats(x,y)[[1]]
y. <- matchMats(x,y)[[2]]
levels(x.[,2]);levels(y.[,2])
x.[,2] <- as.character(x.[,2])
y.[,2] <- as.character(y.[,2])
x.[,2];y.[,2]
mean.g(x.[,-1:-2],x.[,2])
mean.g(y.[,-1:-2],x.[,2])


@ 

%\subsection{}

%% %%Figure construction
%% <<echo=false,results=hide,label=fig1,include=false>>=
%% @ 


%% %%Figure plotting
%% \begin{figure} 
%% \begin{center} 
%% <<label=fig1,fig=TRUE,echo=false>>=
%% <<fig1>> 
%% @ 
%% \end{center} 
%% \caption{}
%% \label{fig:one}
%% \end{figure}


%% %%Activate for bibtex vibliography
%% \cite{goossens93}
%% \bibliographystyle{plain}
%% \bibliography{/Users/Aeolus/Documents/bibtex/biblib}


\end{document}  


